# Site settings
title: Tom Hudson
email: youremailaddress@gmail.com
description: Welcome to my personal webpage detailing my research themes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomshudson.github.io" # the base hostname & protocol for your site
author: Tom Hudson
street_address: 
city: 
state: 
zip_code: 
country:
phone: 

icon: fas fa-mountain # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/TomSHudson
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/tom-hudson-4628218b
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
remote_theme: andrewbanchich/dimension-jekyll-theme

sass:
style: compressed