# Site settings
title: Tom Hudson Personal Website
description: A website describing Tom Hudson's research.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tom Hudson
user_description: I am a seismologist, focussed on applying novel technologies to shed light on Earth systems that are particularly pertinent for society. I'm currently particularly excited about harnessing the potential of fibreoptic sensing and seismic nodes to study glacier processes and new ways of exploring for critical minerals.
user_title: Academic
email: thomas.hudson@eaps.ethz.ch
twitter_username: TomSHudson
github_username:  TomSHudson
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
