# Site settings
title: Tom Hudson
email: thomas.hudson@earth.ox.ac.uk
description: I'm a seismologist with expertise using very small earthquakes to study fluid processes at various scales, from metres below the surface at glaciers to 10s km into Earth's crust at volcanoes. I focus on systems that are particularly pertinent to society. Below you can explore current projects, publications and software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomshudson.github.io" # the base hostname & protocol for your site
author: Tom Hudson
street_address: 
city: 
state: 
zip_code: 
country:
phone: 

icon: "\f6fc" #fa-mountain # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/TomSHudson
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/tom-hudson-4628218b
pinterest_url:
slack_url:
twitter_url: https://twitter.com/TomSHudson

# Build settings
markdown: kramdown
remote_theme: andrewbanchich/dimension-jekyll-theme

sass:
style: compressed